baseURL = "https://ekanshgoenka.com/"
languageCode = "en-us"
title = "Ekansh Goenka"

[markup.goldmark.renderer]
  unsafe = true

[params]
  tagline = "helly · belly · shmelly"
  github  = "https://github.com/ekanshgoenka"
  youtube = "https://youtube.com/@bytecolony"
  itchio  = "https://ekanshgoenka.itch.io"
