baseURL = "https://ekanshgoenka.com/"
languageCode = "en-us"
title = "Ekansh Goenka"

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[markup.highlight]
  codeFences = true
  noClasses = false
  lineNos = false

[params]
  tagline = "helly · belly · shmelly"
  github  = "https://github.com/ekansh38"
  youtube = "https://www.youtube.com/@byte_colony"
  itchio  = "https://byte-colony.itch.io/"
  email   = "ekansh@ekanshgoenka.com"
